[package]
name = "adv2025"
version = "0.1.0"
edition = "2024"

[dependencies]
itertools = "0.14.0"
log = "0.4.28"
pretty_env_logger = "0.5.0"

[[bin]]
name = "day1"
path = "src/day1.rs"

[[bin]]
name = "day2"
path = "src/day2.rs"

[[bin]]
name = "day3"
path = "src/day3.rs"
